# Generated by Django 2.0.1 on 2018-01-12 18:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('meals', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meal_id', models.IntegerField()),
                ('name', models.CharField(max_length=200)),
                ('season', models.CharField(max_length=200)),
                ('last_made', models.DateTimeField(verbose_name='date published')),
            ],
        ),
        migrations.AlterField(
            model_name='direction',
            name='meal_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='meals.Recipe'),
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='meal_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='meals.Recipe'),
        ),
        migrations.DeleteModel(
            name='Meal',
        ),
    ]
